# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 09:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarCharacteristic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_car_characteristic', models.IntegerField(default=0)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('parent', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'База авто: Название характеристики',
            },
        ),
        migrations.CreateModel(
            name='CarCharacteristicValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_car_characteristic_value', models.IntegerField(default=0)),
                ('value', models.CharField(max_length=255)),
                ('unit', models.CharField(blank=True, max_length=255, null=True)),
                ('id_car_characteristic', models.IntegerField(default=0)),
                ('id_car_modification', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'База авто: Значение характеристик автомобиля',
            },
        ),
        migrations.CreateModel(
            name='CarGeneration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_car_generation', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('year_begin', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('year_end', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('id_car_model', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'База авто: Поколение моделей',
            },
        ),
        migrations.CreateModel(
            name='CarMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_car_mark', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('name_rus', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'База авто: Марка автомобиля',
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_car_model', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('name_rus', models.CharField(blank=True, max_length=255, null=True)),
                ('id_car_mark', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'База авто: Модель автомобиля',
            },
        ),
        migrations.CreateModel(
            name='CarModification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_car_modification', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('start_production_year', models.IntegerField(blank=True, null=True)),
                ('end_production_year', models.IntegerField(blank=True, null=True)),
                ('price_min', models.IntegerField(blank=True, null=True)),
                ('price_max', models.IntegerField(blank=True, null=True)),
                ('id_car_model', models.IntegerField(default=0)),
                ('id_car_serie', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'База авто: Модификация автомобиля',
            },
        ),
        migrations.CreateModel(
            name='CarSerie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_car_serie', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('id_car_model', models.IntegerField(default=0)),
                ('id_car_generation', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'База авто: Серия автомобиля',
            },
        ),
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'База авто: Вид транспорта',
            },
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vk_token', models.CharField(blank=True, max_length=255, null=True)),
                ('vk_extra_data', models.CharField(blank=True, max_length=10000, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('additional_contacts', models.CharField(blank=True, max_length=1000, null=True)),
                ('email_confirmed', models.BooleanField(default=False)),
                ('email_confirm_code', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_confirmed', models.BooleanField(default=False)),
                ('phone_confirm_code', models.CharField(blank=True, max_length=255, null=True)),
                ('response_time', models.CharField(blank=True, max_length=32, null=True)),
                ('response_rate', models.CharField(blank=True, max_length=32, null=True)),
                ('honors', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Клиенты: Данные клиента',
            },
        ),
        migrations.AddField(
            model_name='carmark',
            name='id_car_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ptpgo.CarType'),
        ),
    ]
