# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 13:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'City',
            },
        ),
        migrations.CreateModel(
            name='ClientPhotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='client_photos/')),
                ('updated', models.DateTimeField(default=datetime.datetime.now, verbose_name='updated')),
            ],
            options={
                'verbose_name': 'ClientPhoto',
            },
        ),
        migrations.CreateModel(
            name='ClientRatings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(default=0.0)),
                ('updated', models.DateTimeField(default=datetime.datetime.now, verbose_name='updated')),
            ],
            options={
                'verbose_name': 'ClientRating',
            },
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=1000)),
                ('fio', models.CharField(max_length=1000)),
                ('about', models.CharField(max_length=10000)),
                ('phone', models.CharField(max_length=1000)),
                ('additional_contacts', models.CharField(max_length=1000)),
                ('registered', models.DateTimeField(default=datetime.datetime.now, verbose_name='registered')),
                ('updated', models.DateTimeField(default=datetime.datetime.now, verbose_name='updated')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ptpgo.City')),
            ],
            options={
                'verbose_name': 'Client',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Country',
            },
        ),
        migrations.CreateModel(
            name='Tokens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=1000)),
                ('last_login', models.DateTimeField(default=datetime.datetime.now, verbose_name='last login')),
                ('last_activity', models.DateTimeField(default=datetime.datetime.now, verbose_name='last activity')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ptpgo.Clients')),
            ],
            options={
                'verbose_name': 'Token',
            },
        ),
        migrations.AddField(
            model_name='clients',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ptpgo.Country'),
        ),
        migrations.AddField(
            model_name='clients',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ptpgo.ClientPhotos'),
        ),
        migrations.AddField(
            model_name='clients',
            name='rating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ptpgo.ClientRatings'),
        ),
        migrations.AddField(
            model_name='clientratings',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ptpgo.Clients'),
        ),
        migrations.AddField(
            model_name='clientphotos',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ptpgo.Clients'),
        ),
    ]
