# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 11:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ptpgo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientNotificationsLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(max_length=255)),
                ('notification_data', models.CharField(max_length=255)),
                ('destination_system', models.CharField(max_length=255)),
                ('destination_details', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='added')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Клиенты: Лог sms и email уведомлений',
            },
        ),
        migrations.CreateModel(
            name='ClientPhotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='client_photos/')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='added/updated')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Клиенты: Фотографии',
            },
        ),
        migrations.CreateModel(
            name='ClientRatings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(default=0.0)),
                ('rated_by', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='added')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Клиенты: Рейтинг',
            },
        ),
        migrations.CreateModel(
            name='ClientSiteNotifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(max_length=255)),
                ('notification_data', models.CharField(max_length=255)),
                ('checked', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='added')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Клиенты: Уведомления на сайте',
            },
        ),
        migrations.AddField(
            model_name='clients',
            name='vk_user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
