# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 11:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ptpgo', '0002_auto_20160406_1102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientnotificationslog',
            old_name='client',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='clientsitenotifications',
            old_name='client',
            new_name='user',
        ),
    ]
