# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 11:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ptpgo', '0003_auto_20160406_1147'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarCharacteristic',
        ),
        migrations.DeleteModel(
            name='CarCharacteristicValue',
        ),
        migrations.DeleteModel(
            name='CarGeneration',
        ),
        migrations.RemoveField(
            model_name='carmark',
            name='id_car_type',
        ),
        migrations.DeleteModel(
            name='CarModel',
        ),
        migrations.DeleteModel(
            name='CarModification',
        ),
        migrations.DeleteModel(
            name='CarSerie',
        ),
        migrations.DeleteModel(
            name='CarMark',
        ),
        migrations.DeleteModel(
            name='CarType',
        ),
    ]
