# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-15 12:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ptpgo', '0005_auto_20160205_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarCharacteristic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('parent', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Название характеристики',
            },
        ),
        migrations.CreateModel(
            name='CarCharacteristicValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('unit', models.CharField(blank=True, max_length=255, null=True)),
                ('car_characteristic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ptpgo.CarCharacteristic')),
            ],
            options={
                'verbose_name_plural': 'Значение характеристик автомобиля',
            },
        ),
        migrations.CreateModel(
            name='CarGeneration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('year_begin', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('year_end', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Поколение моделей',
            },
        ),
        migrations.CreateModel(
            name='CarMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_rus', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Марка автомобиля',
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_rus', models.CharField(blank=True, max_length=255, null=True)),
                ('car_mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ptpgo.CarMark')),
            ],
            options={
                'verbose_name_plural': 'Модель автомобиля',
            },
        ),
        migrations.CreateModel(
            name='CarModification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_production_year', models.IntegerField(blank=True, null=True)),
                ('end_production_year', models.IntegerField(blank=True, null=True)),
                ('price_min', models.IntegerField(blank=True, null=True)),
                ('price_max', models.IntegerField(blank=True, null=True)),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ptpgo.CarModel')),
            ],
            options={
                'verbose_name_plural': 'Модификация автомобиля',
            },
        ),
        migrations.CreateModel(
            name='CarSerie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('car_generation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ptpgo.CarGeneration')),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ptpgo.CarModel')),
            ],
            options={
                'verbose_name_plural': 'Серия автомобиля',
            },
        ),
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Вид транспорта',
            },
        ),
        migrations.AddField(
            model_name='carmodification',
            name='car_serie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ptpgo.CarSerie'),
        ),
        migrations.AddField(
            model_name='carmark',
            name='car_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ptpgo.CarType'),
        ),
        migrations.AddField(
            model_name='cargeneration',
            name='car_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ptpgo.CarModel'),
        ),
        migrations.AddField(
            model_name='carcharacteristicvalue',
            name='car_modification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ptpgo.CarModification'),
        ),
    ]
