# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptpgo', '0005_auto_20160407_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listboat',
            name='boat_build_year',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
