# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-15 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptpgo', '0006_auto_20160215_1205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carmark',
            old_name='car_type',
            new_name='id_car_type',
        ),
        migrations.RemoveField(
            model_name='carcharacteristicvalue',
            name='car_characteristic',
        ),
        migrations.RemoveField(
            model_name='carcharacteristicvalue',
            name='car_modification',
        ),
        migrations.RemoveField(
            model_name='cargeneration',
            name='car_model',
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='car_mark',
        ),
        migrations.RemoveField(
            model_name='carmodification',
            name='car_model',
        ),
        migrations.RemoveField(
            model_name='carmodification',
            name='car_serie',
        ),
        migrations.RemoveField(
            model_name='carserie',
            name='car_generation',
        ),
        migrations.RemoveField(
            model_name='carserie',
            name='car_model',
        ),
        migrations.AddField(
            model_name='carcharacteristic',
            name='id_car_characteristic',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carcharacteristicvalue',
            name='id_car_characteristic',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carcharacteristicvalue',
            name='id_car_characteristic_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carcharacteristicvalue',
            name='id_car_modification',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cargeneration',
            name='id_car_generation',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cargeneration',
            name='id_car_model',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carmark',
            name='id_car_mark',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='id_car_mark',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='id_car_model',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carmodification',
            name='id_car_model',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carmodification',
            name='id_car_modification',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carmodification',
            name='id_car_serie',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carserie',
            name='id_car_generation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carserie',
            name='id_car_model',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carserie',
            name='id_car_serie',
            field=models.IntegerField(default=0),
        ),
    ]
