# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-16 13:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ptpgo', '0007_auto_20160215_1222'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientNotificationsLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(max_length=255)),
                ('notification_data', models.CharField(max_length=255)),
                ('destination_system', models.CharField(max_length=255)),
                ('destination_details', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='added')),
            ],
            options={
                'verbose_name_plural': 'Клиенты: Лог sms и email уведомлений',
            },
        ),
        migrations.CreateModel(
            name='ClientSiteNotifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(max_length=255)),
                ('notification_data', models.CharField(max_length=255)),
                ('checked', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='added')),
            ],
            options={
                'verbose_name_plural': 'Клиенты: Уведомления на сайте',
            },
        ),
        migrations.CreateModel(
            name='ListBoat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boat_type', models.CharField(blank=True, max_length=255, null=True)),
                ('boat_builder', models.CharField(blank=True, max_length=255, null=True)),
                ('boat_model', models.CharField(blank=True, max_length=255, null=True)),
                ('boat_length', models.CharField(blank=True, max_length=255, null=True)),
                ('boat_build_year', models.CharField(max_length=32)),
                ('location', models.CharField(blank=True, max_length=1000, null=True)),
                ('description', models.CharField(blank=True, max_length=10000, null=True)),
                ('amenities', models.CharField(blank=True, max_length=10000, null=True)),
                ('guest_capacity', models.IntegerField(default=0)),
                ('cabins', models.IntegerField(default=0)),
                ('single_beds', models.IntegerField(default=0)),
                ('double_beds', models.IntegerField(default=0)),
                ('avail_date_ranges', models.CharField(blank=True, max_length=1000, null=True)),
                ('not_avail_date_ranges', models.CharField(blank=True, max_length=1000, null=True)),
                ('with_captain', models.BooleanField(default=True)),
                ('fuel_included', models.BooleanField(default=True)),
                ('day_price', models.CharField(blank=True, max_length=255, null=True)),
                ('week_price', models.CharField(blank=True, max_length=255, null=True)),
                ('month_price', models.CharField(blank=True, max_length=255, null=True)),
                ('canceled', models.BooleanField(default=False)),
                ('timestamp_edited', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date updated')),
                ('timestamp_added', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date listed')),
            ],
            options={
                'verbose_name_plural': 'Объявления: Водный транспорт',
            },
        ),
        migrations.CreateModel(
            name='ListBoatPhotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='boat_photos/')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='added')),
                ('boat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ptpgo.ListBoat')),
            ],
            options={
                'verbose_name_plural': 'Объявления: Водный транспорт - фотографии',
            },
        ),
        migrations.AlterModelOptions(
            name='carcharacteristic',
            options={'verbose_name_plural': 'База авто: Название характеристики'},
        ),
        migrations.AlterModelOptions(
            name='carcharacteristicvalue',
            options={'verbose_name_plural': 'База авто: Значение характеристик автомобиля'},
        ),
        migrations.AlterModelOptions(
            name='cargeneration',
            options={'verbose_name_plural': 'База авто: Поколение моделей'},
        ),
        migrations.AlterModelOptions(
            name='carmark',
            options={'verbose_name_plural': 'База авто: Марка автомобиля'},
        ),
        migrations.AlterModelOptions(
            name='carmodel',
            options={'verbose_name_plural': 'База авто: Модель автомобиля'},
        ),
        migrations.AlterModelOptions(
            name='carmodification',
            options={'verbose_name_plural': 'База авто: Модификация автомобиля'},
        ),
        migrations.AlterModelOptions(
            name='carserie',
            options={'verbose_name_plural': 'База авто: Серия автомобиля'},
        ),
        migrations.AlterModelOptions(
            name='cartype',
            options={'verbose_name_plural': 'База авто: Вид транспорта'},
        ),
        migrations.AlterModelOptions(
            name='clientphotos',
            options={'verbose_name_plural': 'Клиенты: Фотографии'},
        ),
        migrations.AlterModelOptions(
            name='clientratings',
            options={'verbose_name_plural': 'Клиенты: Рейтинг'},
        ),
        migrations.AlterModelOptions(
            name='clients',
            options={'verbose_name_plural': 'Клиенты: Аккаунт'},
        ),
        migrations.AlterModelOptions(
            name='tokens',
            options={'verbose_name_plural': 'Клиенты: Токены авторизации'},
        ),
        migrations.RemoveField(
            model_name='clientphotos',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='clientratings',
            name='updated',
        ),
        migrations.AddField(
            model_name='clientphotos',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='added/updated'),
        ),
        migrations.AddField(
            model_name='clientratings',
            name='rated_by',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clientratings',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='added'),
        ),
        migrations.AddField(
            model_name='clients',
            name='response_time',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='confirm_code',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='fio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tokens',
            name='token',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='listboat',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ptpgo.Clients'),
        ),
        migrations.AddField(
            model_name='clientsitenotifications',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ptpgo.Clients'),
        ),
        migrations.AddField(
            model_name='clientnotificationslog',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ptpgo.Clients'),
        ),
    ]
