# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-17 12:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ptpgo', '0008_auto_20160216_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderBoat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_range_selected', models.CharField(max_length=1000)),
                ('status_order', models.CharField(max_length=255)),
                ('status_payment', models.CharField(max_length=255)),
                ('status_cancel_reason', models.CharField(blank=True, max_length=1000, null=True)),
                ('status_fail_reason', models.CharField(blank=True, max_length=1000, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='order date/time')),
            ],
            options={
                'verbose_name_plural': 'Заказы: Аренда водного транспорта',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_for', models.IntegerField(default=0)),
                ('content', models.CharField(max_length=10000)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='review added date/time')),
            ],
            options={
                'verbose_name_plural': 'Заказы: Отзывы по сделке',
            },
        ),
        migrations.AlterModelOptions(
            name='tokens',
            options={'verbose_name_plural': 'Клиенты: Токены авторизации пользователей'},
        ),
        migrations.RemoveField(
            model_name='clients',
            name='confirm_code',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='fio',
        ),
        migrations.RemoveField(
            model_name='listboat',
            name='day_price',
        ),
        migrations.RemoveField(
            model_name='listboat',
            name='month_price',
        ),
        migrations.RemoveField(
            model_name='listboat',
            name='not_avail_date_ranges',
        ),
        migrations.RemoveField(
            model_name='listboat',
            name='week_price',
        ),
        migrations.AddField(
            model_name='clients',
            name='email_confirm_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clients',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='honors',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clients',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='phone_confirm_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='phone_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clients',
            name='response_rate',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='listboat',
            name='engines_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listboat',
            name='horsepower_per_engine',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='listboat',
            name='speed_per_hour',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='response_time',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='reviews',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ptpgo.Clients'),
        ),
        migrations.AddField(
            model_name='orderboat',
            name='boat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ptpgo.ListBoat'),
        ),
        migrations.AddField(
            model_name='orderboat',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ptpgo.Clients'),
        ),
    ]
