# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-18 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptpgo', '0009_auto_20160217_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthFacebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AuthGooglePlus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_plus_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AuthVk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vk_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='clients',
            name='facebook_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='google_plus_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='vk_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='password',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
