# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-21 13:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ptpgo', '0010_auto_20160218_1207'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthFacebook',
        ),
        migrations.DeleteModel(
            name='AuthGooglePlus',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='facebook_id',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='google_plus_id',
        ),
    ]
