# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-25 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptpgo', '0011_auto_20160221_1316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authvk',
            old_name='vk_id',
            new_name='vk_user_id',
        ),
        migrations.RenameField(
            model_name='clients',
            old_name='vk_id',
            new_name='vk_user_id',
        ),
        migrations.AddField(
            model_name='authvk',
            name='access_token',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='authvk',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='authvk',
            name='expires_in',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='authvk',
            name='profile',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
