# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-25 10:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ptpgo', '0012_auto_20160225_1013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authvk',
            options={'verbose_name_plural': 'Клиенты: Авторизация через vk.com'},
        ),
    ]
