# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-25 10:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ptpgo', '0013_auto_20160225_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='authvk',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated'),
        ),
    ]
