# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 08:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ptpgo', '0014_authvk_updated'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthVk',
        ),
        migrations.RemoveField(
            model_name='clientnotificationslog',
            name='client',
        ),
        migrations.RemoveField(
            model_name='clientphotos',
            name='client',
        ),
        migrations.RemoveField(
            model_name='clientratings',
            name='client',
        ),
        migrations.RemoveField(
            model_name='clientsitenotifications',
            name='client',
        ),
        migrations.RemoveField(
            model_name='listboat',
            name='client',
        ),
        migrations.RemoveField(
            model_name='listboatphotos',
            name='boat',
        ),
        migrations.RemoveField(
            model_name='orderboat',
            name='boat',
        ),
        migrations.RemoveField(
            model_name='orderboat',
            name='client',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='client',
        ),
        migrations.RemoveField(
            model_name='tokens',
            name='client',
        ),
        migrations.DeleteModel(
            name='ClientNotificationsLog',
        ),
        migrations.DeleteModel(
            name='ClientPhotos',
        ),
        migrations.DeleteModel(
            name='ClientRatings',
        ),
        migrations.DeleteModel(
            name='Clients',
        ),
        migrations.DeleteModel(
            name='ClientSiteNotifications',
        ),
        migrations.DeleteModel(
            name='ListBoat',
        ),
        migrations.DeleteModel(
            name='ListBoatPhotos',
        ),
        migrations.DeleteModel(
            name='OrderBoat',
        ),
        migrations.DeleteModel(
            name='Reviews',
        ),
        migrations.DeleteModel(
            name='Tokens',
        ),
    ]
