# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 12:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ptpgo', '0015_auto_20160331_0842'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vk_token', models.CharField(blank=True, max_length=255, null=True)),
                ('vk_extra_data', models.CharField(blank=True, max_length=10000, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('additional_contacts', models.CharField(blank=True, max_length=1000, null=True)),
                ('email_confirmed', models.BooleanField(default=False)),
                ('email_confirm_code', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_confirmed', models.BooleanField(default=False)),
                ('phone_confirm_code', models.CharField(blank=True, max_length=255, null=True)),
                ('response_time', models.CharField(blank=True, max_length=32, null=True)),
                ('response_rate', models.CharField(blank=True, max_length=32, null=True)),
                ('honors', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Клиенты: Данные клиента',
            },
        ),
    ]
